name: Frontend CI

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      node-version:
        required: true
        type: string
      frontend-base-version:
        description: Version of the Plone frontend container base image
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: frontend

jobs:
  checks:
    name: "Frontend: Lint, test, and build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@{{ versions.gha_version_checkout }}

      - name: Setup Node.js
        uses: actions/setup-node@{{ versions.gha_version_setup_node }}
        with:
          node-version: {{ "${{ inputs.node-version }}" }}

      - name: Install and enable Corepack
        run: |
          npm install --global corepack@latest
          corepack enable

      - name: Install frontend
        working-directory: {{ "${{ inputs.working-directory }}" }}
        run: make install

      - name: Lint frontend
        working-directory: {{ "${{ inputs.working-directory }}" }}
        run: make lint

      - name: Test frontend
        working-directory: {{ "${{ inputs.working-directory }}" }}
        run: make test

      - name: Build frontend
        working-directory: {{ "${{ inputs.working-directory }}" }}
        run: make build

  release:
    name: "Frontend: Build and publish container image"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@{{ versions.gha_version_plone_meta }}
    needs: [checks]
    permissions:
      contents: read
      packages: write
    with:
      base-tag: {{ "${{ inputs.base-tag }}" }}
      image-name-prefix: {{ "${{ inputs.image-name-prefix }}" }}
      image-name-suffix: {{ "${{ inputs.image-name-suffix }}" }}
      working-directory: {{ "${{ inputs.working-directory }}" }}
      build-args: |
        VOLTO_VERSION={{ "${{ inputs.frontend-base-version }}" }}
      push: {{ "${{ github.event_name != 'pull_request' }}" }}
    secrets:
      username: {{ "${{ github.actor }}" }}
      password: {{ "${{ secrets.GITHUB_TOKEN }}" }}

  report:
    name: "Final report"
    if: {{ "${{ always() }}" }}
    runs-on: ubuntu-latest
    needs: [checks, release]
    steps:
      - name: Write report
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| checks | {{ "${{ needs.checks.result }}" }} |' >> $GITHUB_STEP_SUMMARY
          echo '| release | {{ "${{ needs.release.result }}" }} |' >> $GITHUB_STEP_SUMMARY
