name: "{{ cookiecutter.python_package_name }} CI"

on:
  push:

env:
  python-version: "{{ cookiecutter.__gha_python_version }}"
  plone-version: "{{ cookiecutter.__gha_plone_version }}"

jobs:
  lint:
    name: "Backend: Lint"
    uses: plone/meta/.github/workflows/backend-lint.yml@{{ cookiecutter.__gha_version_plone_meta }}
    with:
      python-version: {{ "${{ env.python-version }}" }}
      plone-version: {{ "${{ env.plone-version }}" }}

  test:
    name: "Backend: Test"
    uses: plone/meta/.github/workflows/backend-pytest.yml@{{ cookiecutter.__gha_version_plone_meta }}
    strategy:
      matrix:
        python-version: {{ cookiecutter.__gha_python_versions }}
        plone-version: {{ cookiecutter.__gha_plone_versions }}
    with:
      python-version: {{ "${{ matrix.python-version }}" }}
      plone-version: {{ "${{ matrix.plone-version }}" }}

  coverage:
    name: "Backend: Test Coverage"
    uses: plone/meta/.github/workflows/backend-pytest-coverage.yml@{{ cookiecutter.__gha_version_plone_meta }}
    needs:
      - test
    with:
      python-version: {{ "${{ env.python-version }}" }}
      plone-version: {{ "${{ env.plone-version }}" }}
