name: Unit Tests
on:
  push:
    paths:
      - "*.js"
      - "*.json"
      - "*.yaml"
      - "packages/**"
      - ".github/workflows/unit.yml"

env:
  NODE_VERSION: {{ cookiecutter.__gha_version_node }}

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}

      - name: Use Node.js
        uses: actions/setup-node@{{ cookiecutter.__gha_version_setup_node }}
        with:
          node-version: {{ "${{ env.NODE_VERSION }}" }}

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@{{ cookiecutter.__gha_version_cache }}
        name: Setup pnpm cache
        with:
          path: {{ "${{ env.STORE_PATH }}" }}
          key: {{ "${{ runner.os }}" }}-pnpm-store-{{ "${{ hashFiles('**/pnpm-lock.yaml') }}" }}
          restore-keys: |
            {{ "${{ runner.os }}" }}-pnpm-store-

      - name: Install dependencies
        run: make install

      - name: Unit tests
        run: make ci-test
