packages:
  # all packages in direct subdirs of packages/
  - 'core/packages/*'
  - 'packages/*'

# We need a way to sync the versions of the catalog packages with the one in core
# Probably a script in @plone/scripts
catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@tanstack/react-query': ^5.59.0
  react-aria-components: ^1.6.0
  release-it: 18.1.2
  typescript: ^5.7.3
  vitest: ^2.1.3
  vite: ^5.4.9
