name: {{ cookiecutter.title }} CI

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/backend.yml"
      {%- if cookiecutter.initialize_documentation == '1' %}
      - "docs/**"
      - ".github/workflows/docs.yml"
      - .readthedocs.yaml
      {%- endif %}
      - ".github/workflows/frontend.yml"
      - ".github/workflows/main.yml"
      - "devops/**"
  workflow_dispatch:

jobs:
  config:
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: {{ "${{ needs.config.outputs.base-tag }}" }}
        image-name-prefix: {{ "${{ needs.config.outputs.image-name-prefix }}" }}
        image-name-suffix: backend
        python-version: {{ "${{ needs.config.outputs.python-version }}" }}
        plone-version: {{ "${{ needs.config.outputs.plone-version }}" }}
    if: {{ "${{ needs.config.outputs.backend == 'true' }}" }}
    permissions:
      contents: read
      packages: write

{%- if cookiecutter.initialize_documentation == '1' %}

  docs:
    uses: ./.github/workflows/docs.yml
    needs:
        - config
    with:
        python-version: {{ "${{ needs.config.outputs.python-version }}" }}
        working-directory: docs
    if: {{ "${{ needs.config.outputs.docs == 'true' }}" }}
{%- endif %}

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: {{ "${{ needs.config.outputs.base-tag }}" }}
        image-name-prefix: {{ "${{ needs.config.outputs.image-name-prefix }}" }}
        image-name-suffix: frontend
        node-version: {{ "${{ needs.config.outputs.node-version }}" }}
        volto-version: {{ "${{ needs.config.outputs.volto-version }}" }}
    if: {{ "${{ needs.config.outputs.frontend == 'true' }}" }}
    permissions:
      contents: read
      packages: write

{%- if cookiecutter.devops_cache == '1' %}

  varnish:
    uses: ./.github/workflows/varnish.yml
    needs:
        - config
    with:
        base-tag: {{ "${{ needs.config.outputs.base-tag }}" }}
        image-name-prefix: {{ "${{ needs.config.outputs.image-name-prefix }}" }}
        image-name-suffix: varnish
    if: {{ "${{ needs.config.outputs.varnish == 'true' }}" }}
    permissions:
      contents: read
      packages: write
{%- endif %}

  report:
    name: "Final report"
    if: {{ "${{ always() }}" }}
    runs-on: ubuntu-latest
    needs:
      - config
      - backend
      - frontend
      {%- if cookiecutter.initialize_documentation == '1' %}
      - docs
      {%- endif %}
      {%- if cookiecutter.devops_cache == '1' %}
      - varnish
      {%- endif %}
    steps:
      - name: Write report
        run: |
          {{ "echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY" }}
          {{ "echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY" }}
          {{ "echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY" }}
          {{ "echo '| config | ${{ needs.config.result }} |' >> $GITHUB_STEP_SUMMARY" }}
          {{ "echo '| backend | ${{ needs.backend.result }} |' >> $GITHUB_STEP_SUMMARY" }}
          {%- if cookiecutter.initialize_documentation == '1' %}
          {{ "echo '| docs | ${{ needs.docs.result }} |' >> $GITHUB_STEP_SUMMARY" }}
          {%- endif %}
          {{ "echo '| frontend | ${{ needs.frontend.result }} |' >> $GITHUB_STEP_SUMMARY" }}
          {%- if cookiecutter.devops_cache == '1' %}
          {{ "echo '| varnish | ${{ needs.varnish.result }} |' >> $GITHUB_STEP_SUMMARY" }}
          {%- endif %}
