name: CI

on:
  push:
    paths:
      - "backend/**"
      - "devops/**"
      - ".github/workflows/*.yml"
      - "*.md"
      - "*.toml"
      - "docker-compose*"
      {%- if cookiecutter.has_docs == '1' %}
      - "docs/**"
      - .readthedocs.yaml
      {%- endif %}

  workflow_dispatch:

jobs:
  config:
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: {{ "${{ needs.config.outputs.base-tag }}" }}
        image-name-prefix: {{ "${{ needs.config.outputs.image-name-prefix }}" }}
        image-name-suffix: backend
        python-version: {{ "${{ needs.config.outputs.python-version }}" }}
        plone-version: {{ "${{ needs.config.outputs.plone-version }}" }}
    if: {{ "${{ needs.config.outputs.backend == 'true' }}" }}
    permissions:
      contents: read
      packages: write


  {%- if cookiecutter.has_docs == '1' %}
  docs:
    uses: ./.github/workflows/docs.yml
    needs:
        - config
    with:
      python-version: {{ "${{ needs.config.outputs.python-version }}" }}
    if: {{ "${{ needs.config.outputs.docs == 'true' }}" }}
  {%- endif %}


  {%- if cookiecutter.has_cache == '1' %}
  varnish:
    uses: ./.github/workflows/varnish.yml
    needs:
        - config
    with:
        base-tag: {{ "${{ needs.config.outputs.base-tag }}" }}
        image-name-prefix: {{ "${{ needs.config.outputs.image-name-prefix }}" }}
        image-name-suffix: varnish
    if: {{ "${{ needs.config.outputs.cache == 'true' }}" }}
    permissions:
      contents: read
      packages: write
  {%- endif %}

  report:
    name: "Final report"
    if: {{ "${{ always() }}" }}
    runs-on: ubuntu-latest
    needs:
      - config
      - backend
      {%- if cookiecutter.has_docs == '1' %}
      - docs
      {%- endif %}
      {%- if cookiecutter.has_cache == '1' %}
      - varnish
      {%- endif %}
    steps:
      - name: Write report
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| config | {{ "${{ needs.config.result }}" }} |' >> $GITHUB_STEP_SUMMARY
          echo '| backend | {{ "${{ needs.backend.result }}" }} |' >> $GITHUB_STEP_SUMMARY
          {%- if cookiecutter.has_docs == '1' %}
          echo '| docs | {{ "${{ needs.docs.result }}" }} |' >> $GITHUB_STEP_SUMMARY
          {%- endif %}
          {%- if cookiecutter.has_cache == '1' %}
          echo '| varnish | {{ "${{ needs.varnish.result }}" }} |' >> $GITHUB_STEP_SUMMARY
          {%- endif %}
