name: 'Cookieplone Templates: Setup Python'
description: 'Setup dependencies'
inputs:
  python-version:
    description: 'Python Version'
    required: true
    default: '3.12'
runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: false

    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
          uv-${{ runner.os }}-${{ inputs.python-version }}

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: make install
