name: 'Cookieplone Templates: Setup Python'
description: 'Setup dependencies'
inputs:
  python-version:
    description: 'Python Version'
    required: true
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v8.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache-suffix: uv-${{ runner.os }}-${{ inputs.python-version }}
        enable-cache: true

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: make install
