default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

stages:
  - check
  - test
  - build
  - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  # DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_BACKEND_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/backend
  CONTAINER_FRONTEND_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/frontend
  {%- if cookiecutter.devops_cache == '1' %}
  CONTAINER_VARNISH_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/varnish
  {%- endif %}

check-backend:
  stage: check
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common git
  script:
    - cd backend
    - make lint

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

check-frontend:
  image: node:22-alpine
  stage: check
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common git
    - corepack enable
  script:
    - cd frontend
    - make install
    - make lint
    - make ci-i18n

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


test-backend:
  stage: test
  image: python:3.12-bookworm
  before_script:
    - apt update
    - apt install build-essential python3 python3-dev git -y
  script:
    - cd backend
    - make install
    - make test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test-frontend:
  image: node:22-alpine
  stage: test
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common git
    - corepack enable

  script:
    - cd frontend
    - make install
    - make ci-test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-backend:
  stage: build
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common
  script:
    - set -e # Stop if the execution of any command fails
    - cd backend
    - make build-image
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CONTAINER_BACKEND_RELEASE_IMAGE:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-frontend:
  stage: build
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common

  script:
    - set -e # Stop if the execution of any command fails
    - cd frontend
    - make build-image
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CONTAINER_FRONTEND_RELEASE_IMAGE:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

{%- if cookiecutter.devops_cache == '1' %}
build-varnish:
  stage: build
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common
  script:
    - cd devops/varnish
    - docker build . -t $CONTAINER_VARNISH_RELEASE_IMAGE:latest
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CONTAINER_VARNISH_RELEASE_IMAGE:latest

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
{%- endif %}

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  script:
    - mkdir -p ~/.ssh/
    - touch ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - cd devops
    - eval `ssh-agent -s`
    - echo "${DEPLOY_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    - export TERM=dumb
    - touch .env
    - 'echo "DEPLOY_ENV: ${DEPLOY_ENV}" >> .env'
    - 'echo "DEPLOY_HOST: ${DEPLOY_HOST}" >> .env'
    - 'echo "DEPLOY_PORT: ${DEPLOY_PORT}" >> .env'
    - 'echo "DEPLOY_USER: ${DEPLOY_USER}" >> .env'
    - 'echo "DOCKER_CONFIG: ${DOCKER_CONFIG}" >> .env'
    - 'echo "STACK_NAME: ${STACK_NAME}" >> .env'
    - 'echo "STACK_PARAM: ${CI_COMMIT_TAG}" >> .env'
    - make docker-setup
    - make stack-deploy
  environment: production
# deploy-with-auxiliary-docker-image:
#   stage: deploy
#   variables:
#     REGISTRY: ${CI_REGISTRY}
#     USERNAME: ${CI_REGISTRY_USER}
#     PASSWORD: ${CI_REGISTRY_PASSWORD}
#     REMOTE_HOST: ${DEPLOY_HOST}
#     REMOTE_PORT: ${DEPLOY_PORT}
#     REMOTE_USER: ${DEPLOY_USER}
#     REMOTE_PRIVATE_KEY: "${DEPLOY_SSH_PRIVATE_KEY}"
#     STACK_FILE: devops/stacks/${DEPLOY_HOST}.yml
#     STACK_NAME: ${STACK_NAME}
#     DEPLOY_IMAGE: ghcr.io/kitconcept/docker-stack-deploy:latest
#   script:
#     - docker pull ${DEPLOY_IMAGE}
#     - docker run --rm
#       -v "$(pwd)":/github/workspace
#       -v /var/run/docker.sock:/var/run/docker.sock
#       -e REGISTRY=${REGISTRY}
#       -e USERNAME=${USERNAME}
#       -e PASSWORD=${PASSWORD}
#       -e REMOTE_HOST=${REMOTE_HOST}
#       -e REMOTE_PORT=${REMOTE_PORT}
#       -e REMOTE_USER=${REMOTE_USER}
#       -e REMOTE_PRIVATE_KEY="${REMOTE_PRIVATE_KEY}"
#       -e STACK_FILE=${STACK_FILE}
#       -e STACK_NAME=${STACK_NAME}
#       ${DEPLOY_IMAGE}
#   only:
#     - main
#   environment: production