name: 'Cookieplone Templates: Backend functional tests'
description: 'Generate the codebase and run backend tests'
inputs:
  python-version:
    description: 'Python Version'
    required: true
  node-version:
    description: 'Node Version'
    required: true
  template:
    description: 'Template'
    required: false
    default: "backend_addon"
  name:
    description: 'Name'
    required: false
    default: "collective.addon"
runs:
  using: "composite"
  steps:
    - name: Generate
      uses: ./.github/actions/generate
      with:
        template: ${{ inputs.template }}
        python-version: ${{ inputs.python-version }}

    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: uv-${{ runner.os }}-${{ env.python-version }}-${{ hashFiles( 'collective.addon/pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ env.python-version }}-${{ hashFiles('collective.addon/pyproject.toml') }}
          uv-${{ runner.os }}-${{ env.python-version }}

    - name: Install generated package
      working-directory: ${{ inputs.name }}
      shell: bash
      run: |
        make install

    - name: Run unit tests
      working-directory: ${{ inputs.name }}
      shell: bash
      run: |
        make test
