name: "Cookieplone Templates: CI"
description: "Main workflow for cookieplone-templates"

on:
  push:
  workflow_dispatch:

env:
  node-version: 22.x
  python-version: "3.10"

jobs:

  config:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.vars.outputs.NODE_VERSION }}
      python-version: ${{ steps.vars.outputs.PYTHON_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute several vars needed for the CI
        id: vars
        run: |
          echo "NODE_VERSION=${{ env.node-version }}" >> $GITHUB_OUTPUT
          echo "PYTHON_VERSION=${{ env.python-version }}" >> $GITHUB_OUTPUT

      - name: Test vars
        run: |
          echo 'node-version: ${{ steps.vars.outputs.NODE_VERSION }}'
          echo 'python-version: ${{ steps.vars.outputs.PYTHON_VERSION }}'

  test-variables:
    name: "Test variables: ${{ matrix.python-version }}"
    uses: ./.github/workflows/test-variables.yml
    needs:
      - config
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    with:
        python-version: ${{ matrix.python-version }}

  test-template:
    name: "${{ matrix.template }}: ${{ matrix.python-version }}"
    if: "${{ always() }}"
    needs:
      - config
    uses: ./.github/workflows/test-template.yml
    strategy:
      fail-fast: false
      matrix:
        template:
          - "project"
          - "backend_addon"
          - "frontend_addon"
          - "sub/cache"
          - "sub/frontend_project"
          - "sub/project_settings"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    with:
        node-version: ${{ needs.config.outputs.node-version }}
        python-version: ${{ matrix.python-version }}
        working-directory: ${{ matrix.template }}
