name: Plone Project CI
on:
  push:
    paths:
      - "project/**"
      - ".github/workflows/project.yml"
  workflow_dispatch:

env:
  NODE_VERSION: 22.x

jobs:
  generation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      # git checkout
      - name: Checkout codebase
        uses: actions/checkout@v4

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # python install
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Node setup
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Test
      - name: Run tests
        run: |
          cd project
          python -m pytest tests
