name: Plone Project CI
on:
  push:
    paths:
      - "project/**"
      - ".github/workflows/project.yml"
  workflow_dispatch:

env:
  NODE_VERSION: 20.x
  PYTHON_VERSION: "3.12"

jobs:

  generation:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      # git checkout
      - name: Checkout codebase
        uses: actions/checkout@v4

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # python install
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Test
      - name: Run tests
        run: |
          cd project
          python -m pytest tests

  functional:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate
        working-directory: project
        run: |
          make generate

      - name: Install generated package
        working-directory: project/project-title
        run: |
          make install

      - name: Add to version control all generated files from install
        working-directory: project/project-title
        run: |
          git add .

      - name: Check generated package
        working-directory: project/project-title
        run: |
          make check
