# Check links in all README.mds with awesome_bot
# https://github.com/dkhamsing/awesome_bot
name: readme-link-check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check links in README.mds with awesome_bot
        run: |
          gem install awesome_bot
          awesome_bot --request-delay 1 --allow-dupe --white-list https://astral.sh/uv/install.sh,http://localhost:8080,http://localhost:3000 --files README.md,\templates/add-ons/backend/README.md,templates/add-ons/frontend/README.md,templates/docs/starter/README.md,templates/projects/monorepo/README.md,templates/projects/classic/README.md,templates/sub/cache/README.md,templates/sub/frontend_project/README.md,templates/sub/project_settings/README.md
