# Check links in all README.mds and other *.mds at the repo root with Lychee
# https://github.com/lycheeverse/lychee-action
name: readme-link-check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  readme-link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check links in README.md and other *.md files with Lychee
      id: lychee
      uses: lycheeverse/lychee-action@v2
      with:
        fail: true
        args: >-
          --timeout 5
          --max-retries 2
          --retry-wait-time 10
          --exclude https://www.npmjs.com/
          '*.md'
