name: 'Report key usage'
on:
    workflow_call:
      inputs:
        python-version:
          required: true
          type: string

jobs:
  report:
    name: "Generate a report of keys usage in each template"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ inputs.python-version }}

      # Test
      - name: Run tests
        env:
          REPORT_FORMATS: md
          REPORT_FILENAME: report-keys
        shell: bash
        run: |
          make report-keys-usage
          echo "REPORT_FILE=.reports/${REPORT_FILENAME}.md" >> "$GITHUB_ENV"

      - name: Output reports
        shell: bash
        run: |
          if [ -f "$REPORT_FILE" ]; then
            echo "# Keys usage" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
          fi