name: Variables testing
on:
    workflow_call:
      inputs:
        python-version:
          required: true
          type: string

jobs:
  test:
    name: "Test variable usage"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ inputs.python-version }}

      # Test
      - name: Run tests
        run: |
          uv run pytest tests
