name: Template generation
on:
    workflow_call:
      inputs:
        working-directory:
          required: false
          type: string

jobs:
  generation:
    name: "With Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ inputs.python-version }}

      # Test
      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          uv run pytest tests
