name: Template generation
on:
    workflow_call:
      inputs:
        python-version:
          required: true
          type: string
        node-version:
          required: true
          type: string
        working-directory:
          required: false
          type: string

jobs:

  generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ inputs.python-version }}

      # Test
      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          uv run pytest tests

  functional:
    runs-on: ubuntu-latest
    if: ${{ inputs.working-directory == 'backend_addon' ||  inputs.working-directory == 'frontend_addon'}}
    needs:
      - generation
    env:
      test: ./.github/actions/functional-${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ${{ env.test }}
        with:
          python-version: ${{ inputs.python-version }}
          node-version: ${{ inputs.node-version }}