---
cluster:
  hosts:
    {{ cookiecutter.hostname }}:
      ansible_user: root
      ansible_host: {{ cookiecutter.hostname_or_ip }}
      host: {{ cookiecutter.__devops_host }}
      hostname: {{ cookiecutter.hostname }}
      swarm_node:
        labels:
          type: manager
          env: production

  children:
    cluster_managers:
      children:
        cluster_manager:
          hosts:
            {{ cookiecutter.hostname }}:

        cluster_managers_additional:
          hosts:

    cluster_workers:
      hosts:
